name: checkout Terraform code 

on: 
  push:
    paths:
      - "**/*.tf"

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-check:
    name: Terraform check
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: ./Terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTION_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
            
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: initialise terraform
        run: terraform init


# Implement Checkov scanning for security vulnerabilities

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: ./Terraform
          framework: terraform 

      - name: Terraform fmt
        run: terraform fmt
      - name: Terraform plan
        run: terraform plan
